### ISSUE TITLE
cpu_percent monitoring throws KeyError: 'percpu_usage'

### ISSUE THREAD

**Issue by floek** [decryptus/monit-docker#5]
Hi,

when I run monit-docker with podman I get:
```
# /usr/local/bin/monit-docker -s running --name my_container monit --rsc cpu_percent

ERROR:2023-01-05 07:41:34: 'percpu_usage'
Traceback (most recent call last):
  File "/usr/local/bin/monit-docker", line 1237, in main
    monit_docker()
  File "/usr/local/bin/monit-docker", line 842, in __call__
    r = self.run(container, data)
  File "/usr/local/bin/monit-docker", line 1190, in run
    raise MonitDockerExit(int(self._get_resource_info(rsc, data, container['stats'])))
  File "/usr/local/bin/monit-docker", line 745, in _get_resource_info
    return self._calc_cpu_percent(current['cpu_stats'],
  File "/usr/local/bin/monit-docker", line 637, in _calc_cpu_percent
    online_cpus = len(cur_stats['cpu_usage']['percpu_usage'])
KeyError: 'percpu_usage'
```

Seems like `percpu_usage` is not available in cur_stats:
```python
{'total_usage': 2341398947000, 'usage_in_kernelmode': 789813906, 'usage_in_usermode': 2340609133094}
```

Maybe you can improve error handling.

Best,
floek

**Comment by decryptus** [comment]
Hi @floek,

I never try with podman but I will check, I will do an update soon.

**Comment by decryptus** [comment]
Hi @floek,

It should be ok, now.

Best regards !

**Comment by floek** [comment]
Hi @decryptus ,

just tried 0.0.50 and now it gives me:
```
WARNING:2023-01-16 17:15:25: unable to get online cpus information
```

Any ideas?

Best,
Florian

**Comment by decryptus** [comment]
Yes, it's the result of the patch, no more KeyError but only a warning, which result did you expect ?
I can't calculate if I have no information from podman.
Maybe you should upgrade podman.
https://github.com/containers/podman/pull/15867
Best regards

**Comment by floek** [comment]
I see. Thanks for making clear.
